# Generated by Django 5.1.1 on 2024-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='display_pic',
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
